### PR TITLE
Experimental generic regulation support (Only EN 300 220 for CE currently)

### PR DESCRIPTION
**Pull request by hilt0n**
**Please note this is currently only for testing purpose and should not be used in production (no guarantee given at all regarding regulation compliance).**
    
This implementation aims to provides generic support for radio regulation with a working example of the EN 300 220 regulation (CE sub giga). It can be enabled by adding `regulation="EN_300_220"` in `concentratord` config section.

### It currently supports
- Generic standard selection through concentrator config file (EN_300_220 or None/Empty)
- Additional regulation configuration can be added easily by specifying bands (freq min/max, duty cycle, tx power, window time)
- Ensure the load for each bands is never exceeded for the specified window at any time
- Notify the sender (server) of overflow (and reject packet) immediately even if the packet is scheduled later allowing the server to directly route this packet to other available gateway
- Time slot allocation priority is therefore based on schedule reception time (and not tx time)

### Next steps, feature ideas
- Add a new error in chirpstack_api for duty cycle overflow like `chirpstack_api::gw::TxAckStatus::DutyCycleOverlow` to replace InternalError currently used
- Option in configuration to chose between multiple level for the chosen regulation like:
    - `default` (or not defined) Current behavior when activate (warn in log and reject the packet, send DutyCycleOverlow to server)
    - `debug` or `warn_only` Only warn overlow in log and doesn't notify the server
- Integration with stats module which could return for example current load, max load over window time for every band
- **EDIT 17.01.22** Would be interesting to create trackers only when required, on first packet matching for exemple to avoid creating a tracker for each band if only 1 or 2 bands are effectively used.

### Note
- Only tested with SX1302 and immediate packet queuing, SX1301 should also work, 2G4 not supported
- Need code cleanup and optimization
- Need standard compliance review

The current goal is to discuss about the overall architecture like to which configuration section belongs this new parameters. While we could put that in the gateway configuration, this is more related to channel plan and should be enforced by something more global but that's something to be discussed. 

Any feedback would be really appreciated.

### CODE REVIEW

**Comment by hilt0n** [comment]
Some commits since the initial merge request and a small issue with collision detection which has been fixed. 

Result display on log output (DEBUG level):

**Init**
```
2022-01-17 16:15:05,740 INFO  [libconcentratord::reset] Configuring reset pin, chip: 0, pin: 1
2022-01-17 16:15:05,744 INFO  [chirpstack_concentratord_sx1302::cmd::root] Starting Concentratord SX1302 (version: 3.3.1, docs: https://www.chirpstack.io/concentratord/)
2022-01-17 16:15:05,748 INFO  [libconcentratord::reset] Triggering concentrator reset
[..]
2022-01-17 16:15:08,552 INFO  [libconcentratord::jitqueue] Initializing JIT queue, capacity: 32
2022-01-17 16:15:08,562 INFO  [libconcentratord::regulation::engine] Initializing regulation engine, standard: En300_220, bands: 7
[..]
```

**Immediate packet sent from MQTT broker**
```
<MQTT send immediate packet>
2022-01-17 16:15:15,988 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 7716632
2022-01-17 16:15:15,991 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 8716632
2022-01-17 16:15:15,994 INFO  [libconcentratord::regulation::engine] Band M:868.00-868.60, push new item, airtime: 1.384s, new effective load: 0.04/1.00% (3.8%)
<MQTT send immediate packet>
2022-01-17 16:15:16,370 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 8098663
2022-01-17 16:15:16,375 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 10133132
2022-01-17 16:15:16,378 INFO  [libconcentratord::regulation::engine] Band M:868.00-868.60, push new item, airtime: 1.384s, new effective load: 0.08/1.00% (7.6%)
2022-01-17 16:15:16,975 INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 8716632, freq: 868300000, bw: 125000, mod: LoRa, dr: SF12
2022-01-17 16:15:18,392 INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 10133132, freq: 868300000, bw: 125000, mod: LoRa, dr: SF12
<MQTT send immediate packet>
2022-01-17 16:15:25,445 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 17175362
2022-01-17 16:15:25,451 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 18175362
2022-01-17 16:15:25,454 INFO  [libconcentratord::regulation::engine] Band M:868.00-868.60, push new item, airtime: 1.384s, new effective load: 0.11/1.00% (11.2%)
2022-01-17 16:15:26,427 INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 18175362, freq: 868300000, bw: 125000, mod: LoRa, dr: SF12
2022-01-17 16:15:38,280 DEBUG [libconcentratord::regulation::engine] Duty cycle stats (effective loads):
  [K:863.00-865.00]: 0.00/0.10% (0.0%)
  [L:865.00-868.00]: 0.00/1.00% (0.0%)
  [M:868.00-868.60]: 0.11/1.00% (10.9%)
  [N:868.70-869.20]: 0.00/0.10% (0.0%)
  [P:869.40-869.65]: 0.00/10.00% (0.0%)
  [P:869.70-870.00]: 0.00/100.00% (0.0%)
  [Q:869.70-870.00]: 0.00/1.00% (0.0%)
2022-01-17 16:15:38,607 INFO  [libconcentratord::events] Publishing stats event, stats_id: bba5ff5d-d9dc-441d-8984-90421165d54f, rx_received: 0, rx_received_ok: 0, tx_received: 3, tx_emitted: 3
2022-01-17 16:16:08,282 DEBUG [libconcentratord::regulation::engine] Duty cycle stats (effective loads):
  [K:863.00-865.00]: 0.00/0.10% (0.0%)
  [L:865.00-868.00]: 0.00/1.00% (0.0%)
  [M:868.00-868.60]: 0.10/1.00% (10.1%)
  [N:868.70-869.20]: 0.00/0.10% (0.0%)
  [P:869.40-869.65]: 0.00/10.00% (0.0%)
  [P:869.70-870.00]: 0.00/100.00% (0.0%)
  [Q:869.70-870.00]: 0.00/1.00% (0.0%)
2022-01-17 16:16:08,622 INFO  [libconcentratord::events] Publishing stats event, stats_id: a3896084-9dd7-4196-8746-45bf6ed1e606, rx_received: 0, rx_received_ok: 0, tx_received: 0, tx_emitted: 0
<MQTT send immediate packet with too much power>
2022-01-17 16:16:16,360 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 68090108
2022-01-17 16:16:16,368 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 69090108
2022-01-17 16:16:16,370 WARN  [libconcentratord::regulation::engine] Packet TX power is too high, rejected, tx power: 27, matching tracker: 1
<MQTT send a lot of immediate packets>
2022-01-17 16:16:22,747 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 74478069
2022-01-17 16:16:22,754 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 75478069
2022-01-17 16:16:22,757 INFO  [libconcentratord::regulation::engine] Band M:868.00-868.60, push new item, airtime: 1.384s, new effective load: 0.13/1.00% (13.5%)
[..]
2022-01-17 16:16:26,474 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 78201545
2022-01-17 16:16:26,480 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 106641069
2022-01-17 16:16:26,483 INFO  [libconcentratord::regulation::engine] Band M:868.00-868.60, push new item, airtime: 1.384s, new effective load: 0.97/1.00% (97.2%)
2022-01-17 16:16:26,567 INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 78311069, freq: 868300000, bw: 125000, mod: LoRa, dr: SF12
<Duty cycle reached for this band>
2022-01-17 16:16:27,265 INFO  [libconcentratord::jitqueue] Enqueueing immediate packet, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, current_counter_us: 78993785
2022-01-17 16:16:27,270 DEBUG [libconcentratord::jitqueue] Packet enqueued, downlink_id: ee1a9008-4b18-4af1-a795-43739b6e5406, count_us: 108057569
2022-01-17 16:16:27,273 WARN  [libconcentratord::regulation::engine] Band M:868.00-868.60, max tx time reached, current effective load: 0.972%, estimated overlow: 1.01/1.00% (101.0%)
```

**Comment by brocaar** [comment]
Would you be able to add some tests? In case we would make some changes before merging, then at least we know that the functionality stays the same.

**Comment by hilt0n** [comment]
> Would you be able to add some tests? In case we would make some changes before merging, then at least we know that the functionality stays the same.

Yes, no problem. I will try to find some time for that. Just wanted to know if it makes sense for you before doing unit test as I mainly did functionnal testing.

**Comment by hilt0n** [comment]
I also figured out that this is strongly tight to the power table of the gateway. 

Since there is only 16 slots for power entries and the most interesting values are finally the higher power values for each band, it would make sense to have an insight regarding the certification used (at a least a table containing ideal power) from the power table entries generation aside the antenna gain.

Just an example, for EN300-220, it would be preferable to have power 7, 14 and 27 which can be used over all the bands (7dBm is may be too less but can be used with 100% duty cycle in the band P) but 27 - 7 is 20 and then can't fit into the LUT table.

Just something to discuss later probably.

**Comment by hilt0n** [comment]
I did not find the time yet to implement testing and discover since that there is other considerations to take into account regarding overall architecture. 

I will try to find some time soon but it would be better you take already a look at it before we can have a discussion on the architecture (and some dependencies between few modules)

**Comment by brocaar** [comment]
Hey @hilt0n, it has been quite some time but I'm looking at this again.

My plan is to break this down into pieces to make it easier to implement in different steps. I think the first bit to implement would be an duty-cycle tracker + some configuration framework to configure the configuration like ETSI EN 300 220 configuration and merge this into the `master` branch including some tests.

Then the second bit would be to implement this in the different Concentratord versions (sx1301 / sx1302) per band as configuration option. Maybe it would be a good idea to enable this, but do not enforce it by default. This way the stats would be exposed to ChirpStack without any further impact.

---

To summarize what I'm understanding from looking at your code:

### Configuration / band

* This defines the start - end frequency, max tx power, and duty-cycle allowed in the configuration window time (e.g. 60 minutes).
* There might be overlap in start and end frequencies, in which case the max tx power and duty-cycle can be different.

### Engine / tracker

Per window time interval, this keeps track of the airtime per band. In this part there is quite some complexity in your code and I was wondering if we would be able to reduce the complexity in this part. But I guess this depends on the requirements and I would need your help in this.

---

Questions / confirmations:

* If the window time is 60 minutes / 1 hour, it means that we create buckets aggregated by that interval, is that correct? As well a burst within that window would be allowed (e.g. all airtime could be used at once, but then we need to wait until the start of the next window before we can transmit again), correct? Then each bucket contains the tracked airtime per band.
* Example:
  * Duration::from-secs(0) -->  {K: 10 ms, L: 300 ms, M: 1500ms, ....}
  * Duration::from_secs(60*60) --> {...}
  * Duration::from_secs(60*60*2) --> {...}

In such case if there is something to transmit, we need the following parameters to keep track of the duty-cycle:

* Frequency
* Timestamp of transmission
* TX Power

The first step then would be to lookup the band given the frequency and tx power.

The second step then would be to derive the bucket timestamp from the tx timestamp. If it doesn't exist, it will be created at this point (probably we also want to do some garbage collection to remove buckets with a timestamp in the past at this point).

Now we know the bucket and the band, we know:

* How much airtime can be used within the window time (e.g. 60 minutes * duty-cycle, e.g. 60 minutes * 1% = 36 seconds)
* How much airtime has already been used for that band in that bucket
* If that value + airtime of the packet would still be within the duty-cycle or not

Is this correct?

Then wouldn't we be able to reduce the data-structure to something like:

```rust
pub struct Tracker {
    config: Configuration,
    buckets: HashMap<Duration, HashMap<Band, Duration>>,
}
```

Where:

* `config` contains the band configuration
* `buckets` contains a hashmap with as key the start duration of each bucket.
* The value of the `buckets` hashmap is an other hashmap with as key the `Band` (from the `Configuration`) or something which uniquely identifies the configuration band, and a `Duration` containing the already consumed airtime.


Then we would have something like this to keep track of the duty-cycle:

```rust
impl Tracker {
    pub fn track(freq: u32, tx_power: i8, linear_count: Duration, airtime: Duration) -> Resullt<()> {
        ....
    }
}
```

Probably there would be more methods to also extract stats for reporting to ChirpStack.

Please let me know what I'm missing and if I'm oversimplifying things, probably I'm missing some bits. Your feedback will help me to better understand all the requirements :-)

**Comment by hilt0n** [comment]
Hi @brocaar,

I think the global architecture is correct, there is multiple frequency bands which require to be tracked independantly (may be merged for some regulation but I'm not aware of). 

The window time is not fixed and can be specified by regulation applicant but the standard defines 1 hour as default window time. It should be probably must be changed in configuration if required for any reason.

Regarding the technical aspect now of implementing the calculus of the remaining duty cycle (and let's says we are speaking about only one channel to simplify), I maybe overengineered this part but I tried multiple things and the most efficient and "elegant" approach that I found it to consider the duty cycle as a "moving over the absolute time" value.

You can see this approach as follow :
Overview publish


- Initial time can be calculated easily as you do it above (e.g. 60 minutes * duty-cycle, e.g. 60 minutes * 1% = 36 seconds)
- Reload time is calculated easily also as a percent of the elapsed time for a given period given if remaining time is 0, it will reach the initial time after window period (e.g. from 0s to 36s in 1 hour)
- Remaining time after a TX time is calculated by substracting airtime to remaining time at start time and adding the reload time for the same period. Remaining time can't be higher than initial time.

That's almost done but then we need to optimize things. Like we don't want to keep track of all the previous passed event. We need then to define "milestone" in the past which consume all the pasted events and factorize it a simple value, the remaining time at this milestone. 

My approach is to calculate each time we end with a TX event the remaining time at the specific moment:
Consume publish

It has the following advantages:

- Easy to check if we can schedule a TX event in future even if other TX events are already scheduled
- We have a fine control over the maximal TX event that the tracker is capable of handling (static allocation friendly)
- Far more easy to apprehend (but that personnel)
- Allow to consume easily pasted events (passed time should be factorized into a pair <abs time/remaining time>)

In the end, the data structure like that:
``` go
pub struct Tracker {
    config: Configuration,
    buckets: HashMap<Duration, HashMap<Band, Duration>>,
}
```
is probably close and matches with that except the bucket duration is not "initial time" but more "last milestone time" and should include the remaining time accordingly.

Also, I would like to discuss about the power table which should be calculated knowing the max TX power of each channels as already pointed in #https://github.com/chirpstack/chirpstack-concentratord/pull/25#issuecomment-1219120184 but maybe that's another topic.

**Comment by brocaar** [comment]
Thanks @hilt0n for the call this morning. That clarified a lot :-)

**Comment by hilt0n** [comment]
Thank you @brocaar !

Following our discussions and findings, I updated the 2 schematics:
Overview2 publish

Consume2 publish


Given the following values:

- _Dt_ is duty cycle in percent
- _Tw_ is window time in s (e.g. 3600s)
- _Lmax_ is maximum load

1. As the product is not running before T0, the available load should be 0 and not _Lmax_ at T0
2. _Lmax_ should be _Dt_ * _Tw_ / 2 (18s) instead of _Dt_ * _Tw_  (36s) because 2 TX events burst with _Lmax_ can happens during _Tw_

**Comment by brocaar** [comment]
If Lmax would be 18seconds, how would you do a burst of 36 seconds at the
end of the time window (which should be valid)?

I dont think it would give you time to reload to transmit an other 18sec.

**Comment by hilt0n** [comment]
Yes, it's indeed a limitation of the algo, you can do a burst of 18s every half window time. It respects the standard but has drawback. 
Note that previously, we could have say that it was not possible to do a burst of 72s every 2 hours so it's not so different.

**Comment by brocaar** [comment]
I'm still not sure this is the right approach. I have been thinking about this over the weekend, but I believe the rate at which you reload should be equal at the rate at which you increase the load (1 second per 1 second). As well, I believe the remaining load should always be equal to max load - load (within a window of time). Thus:

If the max load is 2 and the load is 1, then the available load is 1.
If the max load is 2 and the load is 2, then the available load is 0.
...


An example, if you have a window of 4 seconds, and a duty-cycle of 50%, that means the max load is 2 within a window of 4.

In the following example, between T0 - T8 there is a constant load of 2.

```
0 1 2 3 4 5 6 7 8
|x|x| | |x|x| | |
[load: 2]                       <= load T0 - T4
  [load: 2]                     <= load T4 - T8
    [load: 2]
      [load: 2]
        [load: 2]
```

* TX at T0 for 2 seconds.
* Between T2 - T4 no "reload" takes place.
* Starting at T4 TX for 2 seconds.
  * This means that from T4 - T5, a "reload" of 1 second takes place (which is immediately consumed by the TX)
  * The same between T5 and T6.
* From T6 - T8 no "reload" takes place.

If we put this in a graph (we only TX at T0 for 2 seconds and then look at the load per window):

```
0 1 2 3 4 5 6 7 8
|x|x| | | | | | |
[load: 2]                       <= load T0 - T4
  [load: 1]                     <= load T4 - T8
    [load: 0]
      [load: 0]
        [load: 0]
```

Then I believe it would look like this:

image

Thus a load of 1 "slides out of the window" when you look at the load between T1 and T5, meaning at T5 we decrease the load by 1 (or reload by 1) thus the available load is 1.
The same when we take the load between T2 - T6, at which point the load is back to 0 or the available load is 2.

**Comment by brocaar** [comment]
> I'm not sure to understand because the graph doesn't really represent the text above but maybe I got it (correct me if I'm wrong).

I believe it does:

```
0 1 2 3 4 5 6 7 8
|x|x| | | | | | |
```

* Between T0 - T1 we transmit 1 second, thus at T1 the load is 1
* Between T1 - T2 we transmit 1 second, thus at T2 the load is 2
* At T5, the load is 1, because our window is 4, thus it captures T1 - T5. In this window we only transmitted 1 second.
* At T6 the load is 0, because we capture T2 - T6. There was not TX during this window.

```
0 1 2 3 4 5 6 7 8
|x|x| | | | | | |
[load: 2]                       <= load T0 - T4
  [load: 1]                     <= load T4 - T8
    [load: 0]
      [load: 0]
        [load: 0]
```

If we look at the load (thus looking from T(x) - T(x-4):

* T4 = our load was 2 (capturing T0 - T4)
* T5 = our load was 1 (capturing T1 - T5)
* T6 = our load was 0 (capturing (T2 - T6)

>  I fear you will tend to a network which is active only at the beginning of the window time and then nothing for the rest of the window time because it's "open bar" until load is full then same at the next window time.

But that should be something for the NS to decide. E.g. allow consuming all available load at once, or space them over time. There might be an use-case where users want to do a burst of 36 seconds at the beginning (e.g. FUOTA update), or on a shared network you want to avoid that one user consumes all available load (and thus the available load is distributed across different users).

* At the gateway side we should implement compliance with the regulations
* At the NS side we should implement the scheduling strategy

**Comment by brocaar** [comment]
To come back to your proposal:

> Lmax should be Dt * Tw / 2 (18s) instead of Dt * Tw (36s) because 2 TX events burst with Lmax can happens during Tw

It would mean that continuing on the above example of a window of 4 seconds and a duty-cycle of 50%, it means the max load is 1s. If I understand correctly, the reload-rate would be max-load (1) / window (4), thus 0.25 per second.

I don't think it matters if we start with an available load equal to 0 or to max-load at the beginning. Because if the gateway would be idle for the duration equal to the time window, it would reach the max-load. Anyway, in the below examples I will start with an available load of 0:

```
0 1 2 3 4 5 6 7 8
| | | | |x| | |x|
        [load: 2]
```

This would pass using your algorithm:

* Between T0 and T4 we have "reloaded" our available load to 1 sec (4 x 0.25)
* At T4 we TX for 1 second
* Between T4 and T8 we reload (4 x 0.25)
* At T7 we TX for 1 second
* Thus at T8 our load is 2 (50%)

However, this scenario would only allow us to reach a load of 1.75:

```
0 1 2 3 4 5 6 7 8
| | | | | |x| |x|
        [l: 1.75]
```

* Between T0 and T4 we have "reloaded" our available load to 1 sec (4 x 0.25)
* At T4 we have reached the max load of 1, thus between T4 and T5 we do not reload
* At T5 we TX for 1 second
* Between T5 - T8 we reload (3 x 0.25 = 0.75)
* From T7(.25) - T8 we TX for 0.75 seconds, **because we reloaded 3 x 0.25 = 0.75, a 1 second TX would fail**

Thus in this scenario, the allowed duty-cycle of 50% can no longer be reached (0.25 seconds is lost).

**Comment by hilt0n** [comment]
I understand now your approach (my assumptions in the last comment was wrong).
Regarding the algo, it's really interesting and seems to fix the drawbacks of previous solution. 

It will be a bit more resource consuming however as you need to keep track of last window events right ? Not a lot however given the really low duty cycle. 

Yes I agree
> - At the gateway side we should implement compliance with the regulations
> - At the NS side we should implement the scheduling strategy

I based my algo on the fact it should implement also the scheduling aspect which was really limiting the possibilities.
Did you already think on how to implement it ?

**Comment by brocaar** [comment]
I think there is no other way than store the past items until they slide out of the tracked window. Having this information, we can query the load at any time in the tracked timeline:

```
0 1 2 3 4 5 6 7 8
|x|x| | | | | | |
  [load: 1]
```

* At T0 we TX for 2 seconds
* At T4 we want to TX for 1 second
   * We query the load at T5 (end of the planned TX)
   * Load in window T1 - T5 = 1
   * This means we can TX for 1 second (reaching a load of 2 at T5)

```
0 1 2 3 4 5 6 7 8
|x|x| | |x| | | |
  [load: 2]
```

I have made an initial implementation for this in this branch + some tests (maybe I should update these to the above scenarios with a window of 4 and duty-cycle of 50%, or add these to the list):

https://github.com/chirpstack/chirpstack-concentratord/compare/master...feat_duty_cycle

**Comment by brocaar** [comment]
@hilt0n thanks for your help and feedback sessions. The above commit merges this into the `master` branch. Note that this does not yet activate the duty-cycle tracking. I will start working on this now :-)

**Comment by brocaar** [comment]
Some example output:

```
2024-04-04T11:38:24.998Z INFO  [chirpstack_concentratord_sx1302::handler::uplink] Frame received, uplink_id: 3497806811, count_us: 25782188, freq: 868300000, bw: 125000, mod: LoRa, dr: SF11, ftime_received: false, ftime_ns: 0
2024-04-04T11:38:25.426Z INFO  [libconcentratord::jitqueue] Enqueueing timestamped packet, downlink_id: 2714631089, counter_us: 30782188, current_counter_us: 26226881
2024-04-04T11:38:25.426Z INFO  [libconcentratord::regulation::tracker] Item tracked, band: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%], freq: 868300000, tx_power: 14, start_counter_us: 30782188, end_counter_us: 31638188, duration: 856ms
2024-04-04T11:38:29.946Z INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: 2714631089, count_us: 30782188, freq: 868300000, bw: 125000, mod: LoRa, dr: SF11
2024-04-04T11:38:30.099Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%] - current_dc: 0.00%
2024-04-04T11:38:30.100Z INFO  [libconcentratord::events] Publishing stats event, rx_received: 1, rx_received_ok: 1, tx_received: 1, tx_emitted: 1
2024-04-04T11:38:56.258Z INFO  [chirpstack_concentratord_sx1302::handler::uplink] Frame received, uplink_id: 61302902, count_us: 57040389, freq: 868100000, bw: 125000, mod: LoRa, dr: SF12, ftime_received: false, ftime_ns: 0
2024-04-04T11:38:56.755Z INFO  [libconcentratord::jitqueue] Enqueueing timestamped packet, downlink_id: 2507506162, counter_us: 62040389, current_counter_us: 57555927
2024-04-04T11:38:56.755Z INFO  [libconcentratord::regulation::tracker] Item tracked, band: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%], freq: 868100000, tx_power: 14, start_counter_us: 62040389, end_counter_us: 63588389, duration: 1.548s
2024-04-04T11:39:00.100Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%] - current_dc: 0.02%
2024-04-04T11:39:00.100Z INFO  [libconcentratord::events] Publishing stats event, rx_received: 1, rx_received_ok: 1, tx_received: 1, tx_emitted: 0
2024-04-04T11:39:01.213Z INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: 2507506162, count_us: 62040389, freq: 868100000, bw: 125000, mod: LoRa, dr: SF12
2024-04-04T11:39:21.100Z INFO  [libconcentratord::jitqueue] Enqueueing packet on pps, downlink_id: 2536601980, counter_us: 86801871, current_counter_us: 81901052
2024-04-04T11:39:21.100Z INFO  [libconcentratord::regulation::tracker] Item tracked, band: [label: P, freq_min: 869400000, freq_max: 869650000, dc_max: 10.00%], freq: 869525000, tx_power: 14, start_counter_us: 86801871, end_counter_us: 86913871, duration: 112ms
2024-04-04T11:39:21.100Z INFO  [chirpstack_concentratord_sx1302::handler::beacon] Beacon enqueued, beacon_time_gps_epoch: 1396265984s
2024-04-04T11:39:25.963Z INFO  [chirpstack_concentratord_sx1302::handler::jit] Scheduled packet for TX, downlink_id: 2536601980, count_us: 86801871, freq: 869525000, bw: 125000, mod: LoRa, dr: SF9
2024-04-04T11:39:30.101Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: P, freq_min: 869400000, freq_max: 869650000, dc_max: 10.00%] - current_dc: 0.00%
2024-04-04T11:39:30.101Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%] - current_dc: 0.07%
2024-04-04T11:39:30.101Z INFO  [libconcentratord::events] Publishing stats event, rx_received: 0, rx_received_ok: 0, tx_received: 0, tx_emitted: 2
2024-04-04T11:40:00.102Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: P, freq_min: 869400000, freq_max: 869650000, dc_max: 10.00%] - current_dc: 0.00%
2024-04-04T11:40:00.102Z INFO  [libconcentratord::jitqueue] Duty-cyle stats: [label: M, freq_min: 868000000, freq_max: 868600000, dc_max: 1.00%] - current_dc: 0.07%
```

**Comment by brocaar** [comment]
The latest commits in `master` will enable duty-cycle tracking for the EU868 band for the sx1301/2/3 (without enforcing it). Next steps will be to expose this in the stats message (and add a new ack status).

**Comment by brocaar** [comment]
And this has been added to the proto message, example:

```json
{
    ...
    "dutyCycleStats": {
        "regulation": "ETSI_EN_300_220",
        "bands": [
            {
                "name": "P",
                "frequencyMin": 869400000,
                "frequencyMax": 869650000,
                "loadMax": "360s",
                "loadTracked": "0.112s"
            },
            {
                "name": "M",
                "frequencyMin": 868000000,
                "frequencyMax": 868600000,
                "loadMax": "36s",
                "loadTracked": "2.404s"
            }
        ]
    }
}
```

For the completeness, I could add the window but since this is a static value, these are "lost bytes". Knowing the regulation identifier, this value should be known by the receiver side.

**Pull request closed without merging**
